// SPARK Kids 2 — Story Quest
// 20-minute one-to-one online ESL trial lesson for kids who already know
// enough English to read short sentences. Focus: reading short sentences
// aloud in order, with a little guided writing.

export default {
  id: "spark-2",
  code: "SPARK 2",
  title: "Story Quest",
  subtitle: "Reading a short story aloud, plus a little writing practice",
  length: "20 min",
  coreAim: "Get the child reading short sentences aloud with confidence, putting a story in order, and writing one or two simple words.",
  hiddenAssessment: "Reading accuracy and confidence, sentence-level comprehension, sequencing, letter formation, and willingness to read and write in front of the teacher.",
  materials: [
    "1 spin wheel with 5 words, each revealing a full sentence to read",
    "4 flippable sentence cards that tell a short story in order",
    "2 simple words for guided writing practice",
    "2 mystery pictures for a reading-prediction guessing round",
  ],
  pacing: [
    { part: "Cover + hello", time: "3 min" },
    { part: "Game 1: Spin and Read", time: "4 min" },
    { part: "Game 2: Flip and Read the Story", time: "5 min" },
    { part: "Game 3: Write It!", time: "3 min" },
    { part: "Game 4: What Happens Next?", time: "2 min" },
    { part: "Final retell + feedback", time: "3 min" },
  ],

  introSlides: [
    {
      kind: "intro",
      title: "Let's Read a Story!",
      lead: "Today we will read sentences, put a story in order, and even write a little!",
      steps: [
        "Spin and read a sentence",
        "Flip the story cards in order",
        "Write a word",
        "Tell the whole story!",
      ],
    },
  ],

  slides: [
    {
      kind: "wheel",
      title: "Spin and Read!",
      purpose: "Open with a fast game that puts a full sentence in front of the child to read aloud.",
      timing: "4 min",
      teacherScript: ["Spin it!", "Read the sentence to me.", "Can you read it one more time?"],
      supportMoves: ["Point under each word as the child reads.", "If stuck on a word, read it together, then have the child repeat the whole sentence alone."],
      question: "Spin and read what you get!",
      items: [
        { label: "The dog can run.", wheel: "Dog", icon: "dog" },
        { label: "The cat can jump.", wheel: "Cat", icon: "cat" },
        { label: "The lion can roar.", wheel: "Lion", icon: "lion" },
        { label: "The fish can swim.", wheel: "Fish", icon: "fish" },
        { label: "The elephant is big.", wheel: "Elephant", icon: "elephant" },
      ],
    },
    {
      kind: "flipcards",
      cardMode: "text",
      title: "Flip and Read the Story!",
      purpose: "Reveal a 4-part story in order, reading each sentence aloud as it flips.",
      timing: "5 min",
      teacherScript: ["Flip card 1. Read it to me.", "What happens next? Flip card 2.", "Keep going!", "Now read all four together."],
      supportMoves: ["Keep each card flipped so the child can look back while reading the next one.", "After all four, ask the child to read the whole story start to finish."],
      cards: [
        { number: 1, text: "The dog is happy." },
        { number: 2, text: "The dog has a ball." },
        { number: 3, text: "The dog can jump." },
        { number: 4, text: "The dog runs to the park." },
      ],
      starters: ["First…", "Then…", "Then…", "Last…"],
    },
    {
      kind: "write",
      title: "Write It!",
      purpose: "First guided writing task, tied to a word the child just read.",
      timing: "1.5 min",
      teacherScript: ["Can you write the word dog?", "Say each letter as you write it.", "Show me!"],
      word: "dog",
      icon: "dog",
      instruction: "Write the word on your paper.",
    },
    {
      kind: "write",
      title: "Write It Again!",
      purpose: "Second writing task with a new word from the story, for repetition.",
      timing: "1.5 min",
      teacherScript: ["Now can you write the word jump?", "Say each letter as you write it.", "Show me!"],
      word: "jump",
      instruction: "Write the word on your paper.",
    },
    {
      kind: "mystery",
      title: "What Happens Next? 1",
      purpose: "Shift from reading to prediction, reading a sentence starter and guessing the ending.",
      timing: "1 min",
      teacherScript: ["Look! What do you think happens?", "Reveal it!", "Read the sentence: The cat can ___."],
      label: "cat",
      icon: "cat",
      starter: "I think the cat can ___.",
    },
    {
      kind: "mystery",
      title: "What Happens Next? 2",
      purpose: "Repeat the prediction mechanic with a new character.",
      timing: "1 min",
      teacherScript: ["One more! What do you think happens?", "Reveal it!", "Read the sentence: The fish can ___."],
      label: "fish",
      icon: "fish",
      starter: "I think the fish can ___.",
    },
    {
      title: "Tell the Whole Story!",
      purpose: "End with one short retell using first/then/last and everything read today.",
      timing: "2.5 min",
      kidGuide: ["First…", "Then…", "Last…"],
      teacherScript: ["Can you tell me the dog story?", "Use: first, then, last.", "Great reading today!"],
      expectedOutput: ["First the dog is happy.", "Then the dog has a ball and jumps.", "Last the dog runs to the park."],
      sceneIcons: ["dog"],
    },
    {
      kind: "feedback",
      title: "Great Reading!",
      purpose: "Give positive child-facing feedback and a parent-ready summary.",
      timing: "0.5 min",
      childText: ["Great job!", "You read a whole story!", "You even wrote two words!"],
      feedback: {
        strength: "Good sentence-level reading, good sequencing, willing to read aloud and attempt writing, strong listening.",
        target: "Needs more reading fluency practice, needs more confidence with letter formation when writing, needs more exposure to sight words.",
        recommendedPath: "Fun reading and writing lessons with short stories, sentence strips, and guided writing practice.",
      },
    },
  ],
};
