// SPARK Kids: six standalone 20-minute trial classes (2 Beginner, 2 Intermediate, 2 Advanced).
// Each lesson = about 5 minutes of getting-to-know-you questions (including "Why do you want to learn
// English?") followed by about 15 minutes of lesson. Rendered by IgniteLesson.jsx (track="spark-kids").
// Pictures are all reused from the A1 Kids picture library, so nothing new needs to be generated.

export const SPARK_KIDS_LESSONS = {
  "kids-b1": {
    id: "kids-b1",
    code: "Beginner 1",
    level: "Beginner",
    title: "Animal Friends",
    coreAim: "Meet animals and say what you like: cat, dog, bird, fish, rabbit and lion.",
    length: "20 min",
    slides: [
      {type: "title", stage: "Sparks Class", level: "Beginner", title: "Animal Friends", subtitle: "Meet animals and say what you like."},
      {type: "practice", stage: "Get to Know You", heading: "Say Hello!", line: "Hello! My name is ___.", instruction: [["👋", "Wave and say hello,"], ["🗣️", "then tell me your name."]]},
      {type: "wheel", stage: "Get to Know You", heading: "Spin and Tell Me!", items: [{label: "My name"}, {label: "My age"}, {label: "My favorite color"}, {label: "My favorite animal"}, {label: "My favorite food"}, {label: "My family"}], instruction: [["🎡", "Spin the wheel,"], ["🗣️", "then tell me about it."]]},
      {type: "thisorthat", stage: "Get to Know You", heading: "Why English?", pairs: [["To make friends", "For school"], ["To travel", "To play games"]], why: "Tell me more!", instruction: [["⚖️", "Pick one,"], ["🗣️", "then explain your choice."]]},
      {type: "practice", stage: "Get to Know You", heading: "My Reason", line: "I want to learn English because ___.", instruction: [["🌟", "Finish the sentence,"], ["🗣️", "then tell me your reason."]]},
      {type: "vocab", stage: "Animal Friends", heading: "Animals", items: [{label: "cat", pic: "/curriculum/u9-l1/cat.jpg"}, {label: "dog", pic: "/curriculum/u9-l1/dog.jpg"}, {label: "bird", pic: "/curriculum/u9-l1/bird.png"}], instruction: [["👀", "Look at the pictures,"], ["🗣️", "and say each one aloud."]]},
      {type: "vocab", stage: "Animal Friends", heading: "More Animals", items: [{label: "fish", pic: "/curriculum/u9-l1/fish.avif"}, {label: "rabbit", pic: "/curriculum/u2-l3/rabbit.avif"}, {label: "lion", pic: "/curriculum/u9-l1/lion.avif"}], instruction: [["👀", "Look at the pictures,"], ["🗣️", "and say each one aloud."]]},
      {type: "picmatch", stage: "Find It", heading: "Find the Animal", pool: [{label: "cat", pic: "/curriculum/u9-l1/cat.jpg"}, {label: "dog", pic: "/curriculum/u9-l1/dog.jpg"}, {label: "bird", pic: "/curriculum/u9-l1/bird.png"}, {label: "fish", pic: "/curriculum/u9-l1/fish.avif"}, {label: "rabbit", pic: "/curriculum/u2-l3/rabbit.avif"}, {label: "lion", pic: "/curriculum/u9-l1/lion.avif"}], rounds: [{word: "cat", answer: "cat", choices: ["cat", "dog", "bird", "fish"]}, {word: "fish", answer: "fish", choices: ["fish", "bird", "dog"]}, {word: "lion", answer: "lion", choices: ["lion", "rabbit", "cat"]}, {word: "rabbit", answer: "rabbit", choices: ["rabbit", "dog", "bird"]}], instruction: [["👀", "Read the word,"], ["👆", "then tap the right picture."]]},
      {type: "spotlight", stage: "Animal Friends", heading: "What Is It?", pic: "/curriculum/u9-l1/lion.avif", label: "lion", question: "What is it?", answer: "It's a lion.", instruction: [["👂", "Listen,"], ["🗣️", "then say the answer."]]},
      {type: "pickpic", stage: "What Is It?", heading: "Pick the Animal", rounds: [{pic: "/curriculum/u9-l1/dog.jpg", answer: "dog"}, {pic: "/curriculum/u9-l1/bird.png", answer: "bird"}, {pic: "/curriculum/u9-l1/fish.avif", answer: "fish"}], options: ["dog", "bird", "fish"], instruction: [["👀", "Look at the picture,"], ["🗣️", "then pick the right answer."]]},
      {type: "wheel", stage: "Animal Friends", heading: "Spin an Animal!", items: [{label: "cat"}, {label: "dog"}, {label: "bird"}, {label: "fish"}, {label: "rabbit"}, {label: "lion"}], instruction: [["🎡", "Spin the wheel,"], ["🗣️", "then say: I like ___."]]},
      {type: "guesswho", stage: "What's This?", heading: "What's This?", pic: "/curriculum/u9-l1/elephant.jpg", label: "elephant", options: ["elephant", "giraffe", "monkey"], answer: "elephant", instruction: [["👆", "Tap a tile to reveal a piece,"], ["🗣️", "then say your guess before you pick."]]},
      {type: "mystery", stage: "Which Animal?", heading: "Which Animal Is It?", clues: ["It is very big.", "It has a long nose.", "It lives in a zoo."], answer: "elephant", question: "What is it?", instruction: [["🕵️", "Reveal one clue at a time,"], ["🤔", "then guess before the last clue."]], pic: "/curriculum/u9-l1/elephant.jpg"},
      {type: "dice", stage: "Animal Dice", heading: "Animal Dice", dice: [{name: "Start", items: ["I like", "I see", "I have"]}, {name: "Animal", items: ["a cat", "a dog", "a bird", "a fish", "a rabbit", "a lion"]}], instruction: [["🎲", "Roll the dice,"], ["🗣️", "then make a sentence with all three."]]},
      {type: "practice", stage: "Animal Friends", heading: "Tell Me", line: "I like ___. I have a ___.", instruction: [["🗣️", "Say it out loud,"], ["🙅", "without any help this time."]]},
      {type: "landing", stage: "Wrap-Up", heading: "Great Job!", caption: "You can say the names of animals."},
    ],
  },
  "kids-b2": {
    id: "kids-b2",
    code: "Beginner 2",
    level: "Beginner",
    title: "Rainbow Colors",
    coreAim: "Learn six colors and say what color things are.",
    length: "20 min",
    slides: [
      {type: "title", stage: "Sparks Class", level: "Beginner", title: "Rainbow Colors", subtitle: "Learn colors and say what you see."},
      {type: "practice", stage: "Get to Know You", heading: "Say Hello!", line: "Hello! My name is ___.", instruction: [["👋", "Wave and say hello,"], ["🗣️", "then tell me your name."]]},
      {type: "wheel", stage: "Get to Know You", heading: "Spin and Tell Me!", items: [{label: "My name"}, {label: "My age"}, {label: "My favorite color"}, {label: "My favorite animal"}, {label: "My favorite food"}, {label: "My family"}], instruction: [["🎡", "Spin the wheel,"], ["🗣️", "then tell me about it."]]},
      {type: "thisorthat", stage: "Get to Know You", heading: "Why English?", pairs: [["To make friends", "For school"], ["To travel", "To play games"]], why: "Tell me more!", instruction: [["⚖️", "Pick one,"], ["🗣️", "then explain your choice."]]},
      {type: "practice", stage: "Get to Know You", heading: "My Reason", line: "I want to learn English because ___.", instruction: [["🌟", "Finish the sentence,"], ["🗣️", "then tell me your reason."]]},
      {type: "vocab", stage: "Rainbow Colors", heading: "Colors", items: [{label: "red", swatch: "#E53935"}, {label: "blue", swatch: "#1E88E5"}, {label: "yellow", swatch: "#FDD835"}], instruction: [["👀", "Look at the pictures,"], ["🗣️", "and say each one aloud."]]},
      {type: "vocab", stage: "Rainbow Colors", heading: "More Colors", items: [{label: "green", swatch: "#43A047"}, {label: "orange", swatch: "#FB8C00"}, {label: "purple", swatch: "#8E24AA"}], instruction: [["👀", "Look at the pictures,"], ["🗣️", "and say each one aloud."]]},
      {type: "picmatch", stage: "Find It", heading: "Find the Color", pool: [{label: "red", swatch: "#E53935"}, {label: "blue", swatch: "#1E88E5"}, {label: "yellow", swatch: "#FDD835"}, {label: "green", swatch: "#43A047"}, {label: "orange", swatch: "#FB8C00"}, {label: "purple", swatch: "#8E24AA"}], rounds: [{word: "red", answer: "red", choices: ["red", "blue", "yellow", "green"]}, {word: "green", answer: "green", choices: ["green", "blue", "orange"]}, {word: "purple", answer: "purple", choices: ["purple", "yellow", "red"]}, {word: "orange", answer: "orange", choices: ["orange", "green", "blue"]}], instruction: [["👀", "Read the word,"], ["👆", "then tap the right picture."]]},
      {type: "pickpic", stage: "What Color?", heading: "What Color Is It?", rounds: [{pic: "/curriculum/u8-l1/apple.jpg", answer: "red"}, {pic: "/curriculum/u8-l1/banana.jpg", answer: "yellow"}, {pic: "/curriculum/u2-l1/leaf.avif", answer: "green"}], options: ["red", "yellow", "green"], instruction: [["👀", "Look at the picture,"], ["🗣️", "then pick the right answer."]]},
      {type: "wheel", stage: "Rainbow Colors", heading: "Spin a Color!", items: [{label: "red"}, {label: "blue"}, {label: "yellow"}, {label: "green"}, {label: "orange"}, {label: "purple"}], instruction: [["🎡", "Spin the wheel,"], ["🗣️", "then say: I like ___."]]},
      {type: "guesswho", stage: "What's This?", heading: "What's This?", pic: "/curriculum/u2-l3/rainbow.jpg", label: "rainbow", options: ["rainbow", "sun", "leaf"], answer: "rainbow", instruction: [["👆", "Tap a tile to reveal a piece,"], ["🗣️", "then say your guess before you pick."]]},
      {type: "speed", stage: "Color Race", heading: "Color Race", items: ["red", "blue", "yellow", "green", "orange", "purple"], seconds: 45, question: "Say each color out loud.", instruction: [["⏱️", "Beat the clock,"], ["🗣️", "one sentence for each prompt."]], sample: "Red!"},
      {type: "mystery", stage: "Which Fruit?", heading: "Which Fruit Is It?", clues: ["It is yellow.", "Monkeys love it.", "You peel it."], answer: "banana", question: "What is it?", instruction: [["🕵️", "Reveal one clue at a time,"], ["🤔", "then guess before the last clue."]], pic: "/curriculum/u8-l1/banana.jpg"},
      {type: "practice", stage: "Rainbow Colors", heading: "Find It at Home", line: "Find something ___. It's ___.", instruction: [["🗣️", "Say it out loud,"], ["🙅", "without any help this time."]]},
      {type: "landing", stage: "Wrap-Up", heading: "Great Job!", caption: "You can say the colors."},
    ],
  },
  "kids-i1": {
    id: "kids-i1",
    code: "Intermediate 1",
    level: "Intermediate",
    title: "My Day",
    coreAim: "Talk about the things you do every day with simple sentences.",
    length: "20 min",
    slides: [
      {type: "title", stage: "Sparks Class", level: "Intermediate", title: "My Day", subtitle: "Talk about what you do every day."},
      {type: "practice", stage: "Get to Know You", heading: "Say Hello!", line: "Hi! I'm ___. I'm ___ years old. I live in ___.", instruction: [["👋", "Say hello and tell me about you,"], ["🗣️", "then ask me one question."]]},
      {type: "wheel", stage: "Get to Know You", heading: "Spin and Answer!", items: [{label: "What do you like to do after school?"}, {label: "Who is in your family?"}, {label: "Do you have a pet?"}, {label: "What is your favorite food?"}, {label: "What is your favorite subject?"}, {label: "What do you want to be?"}], instruction: [["🎡", "Spin the wheel,"], ["🗣️", "then answer in a full sentence."]]},
      {type: "thisorthat", stage: "Get to Know You", heading: "Why English?", pairs: [["To make friends", "For school"], ["To travel", "For my future job"]], why: "Tell me more! Use because.", instruction: [["⚖️", "Pick one,"], ["🗣️", "then explain your choice."]]},
      {type: "practice", stage: "Get to Know You", heading: "My Reason", line: "I want to learn English because ___. One day I want to ___.", instruction: [["🌟", "Finish the sentences,"], ["🗣️", "then tell me your reasons."]]},
      {type: "vocab", stage: "My Day", heading: "Morning and School", items: [{label: "get up", pic: "/curriculum/u12-routines/get-up.jpg"}, {label: "brush my teeth", pic: "/curriculum/u12-routines/brush-teeth.jpg"}, {label: "go to school", pic: "/curriculum/u12-routines/go-to-school.jpg"}], instruction: [["👀", "Look at the pictures,"], ["🗣️", "and say each one aloud."]]},
      {type: "vocab", stage: "My Day", heading: "Afternoon and Night", items: [{label: "play", pic: "/curriculum/u12-routines/play.jpg"}, {label: "go home", pic: "/curriculum/u12-routines/go-home.jpg"}, {label: "go to bed", pic: "/curriculum/u12-routines/go-to-bed.jpg"}], instruction: [["👀", "Look at the pictures,"], ["🗣️", "and say each one aloud."]]},
      {type: "picorder", stage: "My Day", heading: "Put My Day in Order", items: [{pic: "/curriculum/u12-routines/get-up.jpg", label: "get up"}, {pic: "/curriculum/u12-routines/brush-teeth.jpg", label: "brush my teeth"}, {pic: "/curriculum/u12-routines/go-to-school.jpg", label: "go to school"}, {pic: "/curriculum/u12-routines/play.jpg", label: "play"}, {pic: "/curriculum/u12-routines/go-home.jpg", label: "go home"}, {pic: "/curriculum/u12-routines/go-to-bed.jpg", label: "go to bed"}], instruction: [["🤔", "Think about the order,"], ["👆", "then tap the pictures in order."]]},
      {type: "picmatch", stage: "Find It", heading: "Find It", pool: [{label: "get up", pic: "/curriculum/u12-routines/get-up.jpg"}, {label: "brush my teeth", pic: "/curriculum/u12-routines/brush-teeth.jpg"}, {label: "go to school", pic: "/curriculum/u12-routines/go-to-school.jpg"}, {label: "play", pic: "/curriculum/u12-routines/play.jpg"}, {label: "go home", pic: "/curriculum/u12-routines/go-home.jpg"}, {label: "go to bed", pic: "/curriculum/u12-routines/go-to-bed.jpg"}], rounds: [{word: "get up", answer: "get up", choices: ["get up", "brush my teeth", "go to school", "play"]}, {word: "play", answer: "play", choices: ["play", "go home", "go to bed"]}, {word: "go to school", answer: "go to school", choices: ["go to school", "play", "brush my teeth"]}, {word: "go to bed", answer: "go to bed", choices: ["go to bed", "get up", "go home"]}], instruction: [["👀", "Read the word,"], ["👆", "then tap the right picture."]]},
      {type: "message", stage: "My Day", heading: "How We Say It", lines: ["I *get up* at seven.", "I *go to school* at eight.", "*What do you do* after school? I *play* with my friends."], instruction: [["👀", "Read the sentences,"], ["🗣️", "then say them with your teacher."]]},
      {type: "quiz", stage: "My Day", heading: "Pick the Word", rounds: [{q: "I ___ up at seven.", options: ["get", "gets", "getting"], answer: "get"}, {q: "I ___ to school at eight.", options: ["go", "goes", "going"], answer: "go"}, {q: "I ___ my teeth every night.", options: ["brush", "brushes", "brushing"], answer: "brush"}, {q: "What do you do ___ school?", options: ["after", "at", "on"], answer: "after"}], instruction: [["🤔", "Read the sentence,"], ["👆", "then pick the best answer."]]},
      {type: "build", stage: "Build It", heading: "Build the Sentence", rounds: [{words: ["I", "get", "up", "at", "seven."]}, {words: ["I", "go", "to", "bed", "at", "nine."]}], instruction: [["🧩", "Tap the words in order,"], ["🗣️", "then say the sentence out loud."]]},
      {type: "wheel", stage: "My Day", heading: "Spin a Time!", items: [{label: "6:00"}, {label: "7:00"}, {label: "8:00"}, {label: "3:00"}, {label: "5:00"}, {label: "9:00"}], instruction: [["🎡", "Spin the wheel,"], ["🗣️", "then say: At ___ I ___."]]},
      {type: "dice", stage: "Day Dice", heading: "Day Dice", dice: [{name: "I", items: ["get up", "brush my teeth", "go to school", "play", "go home", "go to bed"]}, {name: "At", items: ["six", "seven", "eight", "three", "five", "nine"]}], instruction: [["🎲", "Roll the dice,"], ["🗣️", "then make a sentence with all three."]]},
      {type: "practice", stage: "My Day", heading: "My Day", line: "I get up at ___. I go to school at ___. After school I ___.", instruction: [["🗣️", "Say it out loud,"], ["🙅", "without any help this time."]]},
      {type: "landing", stage: "Wrap-Up", heading: "Great Job!", caption: "You can talk about your day."},
    ],
  },
  "kids-i2": {
    id: "kids-i2",
    code: "Intermediate 2",
    level: "Intermediate",
    title: "Yummy Food",
    coreAim: "Say what food you like and don't like, and ask a friend.",
    length: "20 min",
    slides: [
      {type: "title", stage: "Sparks Class", level: "Intermediate", title: "Yummy Food", subtitle: "Say what food you like and don't like."},
      {type: "practice", stage: "Get to Know You", heading: "Say Hello!", line: "Hi! I'm ___. I'm ___ years old. I live in ___.", instruction: [["👋", "Say hello and tell me about you,"], ["🗣️", "then ask me one question."]]},
      {type: "wheel", stage: "Get to Know You", heading: "Spin and Answer!", items: [{label: "What do you like to do after school?"}, {label: "Who is in your family?"}, {label: "Do you have a pet?"}, {label: "What is your favorite food?"}, {label: "What is your favorite subject?"}, {label: "What do you want to be?"}], instruction: [["🎡", "Spin the wheel,"], ["🗣️", "then answer in a full sentence."]]},
      {type: "thisorthat", stage: "Get to Know You", heading: "Why English?", pairs: [["To make friends", "For school"], ["To travel", "For my future job"]], why: "Tell me more! Use because.", instruction: [["⚖️", "Pick one,"], ["🗣️", "then explain your choice."]]},
      {type: "practice", stage: "Get to Know You", heading: "My Reason", line: "I want to learn English because ___. One day I want to ___.", instruction: [["🌟", "Finish the sentences,"], ["🗣️", "then tell me your reasons."]]},
      {type: "vocab", stage: "Yummy Food", heading: "Food", items: [{label: "pizza", pic: "/curriculum/u8-l1/pizza.avif"}, {label: "rice", pic: "/curriculum/u8-l1/rice.jpg"}, {label: "egg", pic: "/curriculum/u8-l1/egg.jpg"}], instruction: [["👀", "Look at the pictures,"], ["🗣️", "and say each one aloud."]]},
      {type: "vocab", stage: "Yummy Food", heading: "More Food", items: [{label: "ice cream", pic: "/curriculum/u1-l3/icecream.jpg"}, {label: "cookie", pic: "/curriculum/u1-l1/cookie.webp"}, {label: "milk", pic: "/curriculum/u2-l2/milk.avif"}], instruction: [["👀", "Look at the pictures,"], ["🗣️", "and say each one aloud."]]},
      {type: "picmatch", stage: "Find It", heading: "Find the Food", pool: [{label: "pizza", pic: "/curriculum/u8-l1/pizza.avif"}, {label: "rice", pic: "/curriculum/u8-l1/rice.jpg"}, {label: "egg", pic: "/curriculum/u8-l1/egg.jpg"}, {label: "ice cream", pic: "/curriculum/u1-l3/icecream.jpg"}, {label: "cookie", pic: "/curriculum/u1-l1/cookie.webp"}, {label: "milk", pic: "/curriculum/u2-l2/milk.avif"}], rounds: [{word: "pizza", answer: "pizza", choices: ["pizza", "rice", "egg", "ice cream"]}, {word: "milk", answer: "milk", choices: ["milk", "egg", "rice"]}, {word: "cookie", answer: "cookie", choices: ["cookie", "pizza", "ice cream"]}, {word: "egg", answer: "egg", choices: ["egg", "rice", "milk"]}], instruction: [["👀", "Read the word,"], ["👆", "then tap the right picture."]]},
      {type: "message", stage: "Yummy Food", heading: "Like or Don't Like", lines: ["I *like* pizza. · I *don't like* eggs.", "*Do you like* ice cream? Yes, I *do*. / No, I *don't*.", "My favorite food is *rice*."], instruction: [["👀", "Read the sentences,"], ["🗣️", "then say what you like."]]},
      {type: "thisorthat", stage: "Food", heading: "Which Do You Like?", pairs: [["Pizza", "Rice"], ["Ice cream", "Cookie"], ["Milk", "Juice"]], why: "Say: I like ___ because ___.", instruction: [["⚖️", "Pick one,"], ["🗣️", "then explain your choice."]]},
      {type: "quiz", stage: "Yummy Food", heading: "Pick the Answer", rounds: [{q: "Do you like pizza? Yes, I ___.", options: ["do", "like", "am"], answer: "do"}, {q: "I ___ like eggs. (no)", options: ["don't", "doesn't", "not"], answer: "don't"}, {q: "___ you like milk?", options: ["Do", "Are", "Is"], answer: "Do"}, {q: "My favorite food ___ rice.", options: ["is", "are", "do"], answer: "is"}], instruction: [["🤔", "Read the sentence,"], ["👆", "then pick the best answer."]]},
      {type: "orderup", stage: "Put It in Order", heading: "Put the Chat in Order!", items: ["Do you like pizza?", "Yes, I do. And you?", "I don't like pizza.", "I like rice."], sides: [0, 1, 0, 1], avatars: [{pic: "/curriculum/u1-l1/wavingkid.jpg", label: "Kid"}, {pic: "/curriculum/u4-l1/child.jpg", label: "Friend"}], instruction: [["🤔", "Think about the order of the conversation,"], ["👆", "then tap each line to place it."]]},
      {type: "wheel", stage: "Yummy Food", heading: "Spin a Food!", items: [{label: "pizza"}, {label: "rice"}, {label: "egg"}, {label: "ice cream"}, {label: "cookie"}, {label: "milk"}], instruction: [["🎡", "Spin the wheel,"], ["🗣️", "then say: I like ___ or I don't like ___."]]},
      {type: "practice", stage: "Yummy Food", heading: "My Favorite Food", line: "My favorite food is ___. I don't like ___.", instruction: [["🗣️", "Say it out loud,"], ["🙅", "without any help this time."]]},
      {type: "landing", stage: "Wrap-Up", heading: "Great Job!", caption: "You can say what food you like."},
    ],
  },
  "kids-a1": {
    id: "kids-a1",
    code: "Advanced 1",
    level: "Advanced",
    title: "Yesterday's Adventure",
    coreAim: "Tell a short story about yesterday using the past tense.",
    length: "20 min",
    slides: [
      {type: "title", stage: "Sparks Class", level: "Advanced", title: "Yesterday's Adventure", subtitle: "Tell a story about yesterday."},
      {type: "practice", stage: "Get to Know You", heading: "Introduce Yourself", line: "Hi! My name is ___. I'm ___ years old. I love ___ and I'm good at ___.", instruction: [["👋", "Introduce yourself,"], ["🗣️", "then tell me something surprising about you."]]},
      {type: "speed", stage: "Get to Know You", heading: "Quick Questions", items: ["your family", "your best friend", "your hobby", "your school", "your dream job", "your pet"], seconds: 45, question: "Say one sentence about each.", instruction: [["⏱️", "Beat the clock,"], ["🗣️", "one sentence for each prompt."]], sample: "My best friend is funny."},
      {type: "thisorthat", stage: "Get to Know You", heading: "Why English?", pairs: [["To make friends", "For school"], ["To travel", "For my future job"]], why: "Tell me more! Use because.", instruction: [["⚖️", "Pick one,"], ["🗣️", "then explain your choice."]]},
      {type: "practice", stage: "Get to Know You", heading: "My English Goal", line: "I want to learn English because ___. One day I want to ___ in English.", instruction: [["🌟", "Finish the sentences,"], ["🗣️", "then tell me your English goal."]]},
      {type: "message", stage: "Yesterday", heading: "Yesterday I...", lines: ["Yesterday I *went* to school.", "I *played* with my friends and I *ate* pizza.", "Some verbs change: *go → went*, *eat → ate*, *sleep → slept*."], instruction: [["👀", "Read the sentences,"], ["🗣️", "then tell me about your yesterday."]]},
      {type: "vocab", stage: "Yesterday", heading: "What I Did", items: [{label: "got up", pic: "/curriculum/u12-routines/get-up.jpg"}, {label: "went to school", pic: "/curriculum/u12-routines/go-to-school.jpg"}, {label: "played", pic: "/curriculum/u12-routines/play.jpg"}], instruction: [["👀", "Look at the pictures,"], ["🗣️", "and say each one aloud."]]},
      {type: "vocab", stage: "Yesterday", heading: "What I Did Next", items: [{label: "ate dinner", pic: "/curriculum/u12-routines/eat-dinner.jpg"}, {label: "took a bath", pic: "/curriculum/u12-routines/take-a-bath.jpg"}, {label: "went to bed", pic: "/curriculum/u12-routines/go-to-bed.jpg"}], instruction: [["👀", "Look at the pictures,"], ["🗣️", "and say each one aloud."]]},
      {type: "picorder", stage: "Yesterday", heading: "Put Yesterday in Order", items: [{pic: "/curriculum/u12-routines/story-1-morning.jpg", label: "morning"}, {pic: "/curriculum/u12-routines/story-2-afternoon.jpg", label: "afternoon"}, {pic: "/curriculum/u12-routines/story-3-night.jpg", label: "night"}], instruction: [["🤔", "Think about the order,"], ["👆", "then tap the pictures in order."]]},
      {type: "quiz", stage: "Yesterday", heading: "Pick the Past Word", rounds: [{q: "Yesterday I ___ to school.", options: ["went", "go", "goed"], answer: "went"}, {q: "I ___ pizza for dinner.", options: ["ate", "eat", "eated"], answer: "ate"}, {q: "We ___ in the park.", options: ["played", "play", "plays"], answer: "played"}, {q: "I ___ at nine o'clock.", options: ["slept", "sleeped", "sleep"], answer: "slept"}], instruction: [["🤔", "Read the sentence,"], ["👆", "then pick the best answer."]]},
      {type: "spoterror", stage: "Spot the Error", heading: "Which One Is Right?", rounds: [{a: "I goed to school.", b: "I went to school.", wrongSide: "a", fix: "I went to school.", explain: ""}, {a: "We eated pizza.", b: "We ate pizza.", wrongSide: "a", fix: "We ate pizza.", explain: ""}, {a: "She play with her cat.", b: "She played with her cat.", wrongSide: "a", fix: "She played with her cat.", explain: ""}], instruction: [["🤔", "Say which one has the mistake,"], ["🗣️", "then say the fix out loud."]], pic: "/curriculum/u12-routines/go-to-school.jpg", label: "went to school"},
      {type: "build", stage: "Build It", heading: "Build the Sentence", rounds: [{words: ["Yesterday", "I", "went", "to", "the", "park."]}, {words: ["We", "played", "and", "ate", "pizza."]}], instruction: [["🧩", "Tap the words in order,"], ["🗣️", "then say the sentence out loud."]]},
      {type: "wheel", stage: "Yesterday", heading: "Spin a Question!", items: [{label: "What did you eat?"}, {label: "Who did you play with?"}, {label: "Where did you go?"}, {label: "What did you watch?"}, {label: "What time did you get up?"}, {label: "What did you do after school?"}], instruction: [["🎡", "Spin the wheel,"], ["🗣️", "then answer with a past sentence."]]},
      {type: "dice", stage: "Story Dice", heading: "Story Dice", dice: [{name: "Yesterday I", items: ["went to the park", "played a game", "ate pizza", "watched a movie", "visited my friend", "slept late"]}, {name: "With", items: ["my dad", "my mom", "my friend", "my sister", "my dog", "my class"]}], instruction: [["🎲", "Roll the dice,"], ["🗣️", "then make a sentence with all three."]]},
      {type: "practice", stage: "Yesterday", heading: "My Yesterday", line: "Yesterday I ___. Then I ___. Finally I ___.", instruction: [["🗣️", "Say it out loud,"], ["🙅", "without any help this time."]]},
      {type: "landing", stage: "Wrap-Up", heading: "Great Job!", caption: "You can tell a story about yesterday."},
    ],
  },
  "kids-a2": {
    id: "kids-a2",
    code: "Advanced 2",
    level: "Advanced",
    title: "My Dream Room",
    coreAim: "Describe a room with there is, there are and where things are.",
    length: "20 min",
    slides: [
      {type: "title", stage: "Sparks Class", level: "Advanced", title: "My Dream Room", subtitle: "Describe the room of your dreams."},
      {type: "practice", stage: "Get to Know You", heading: "Introduce Yourself", line: "Hi! My name is ___. I'm ___ years old. I love ___ and I'm good at ___.", instruction: [["👋", "Introduce yourself,"], ["🗣️", "then tell me something surprising about you."]]},
      {type: "speed", stage: "Get to Know You", heading: "Quick Questions", items: ["your family", "your best friend", "your hobby", "your school", "your dream job", "your pet"], seconds: 45, question: "Say one sentence about each.", instruction: [["⏱️", "Beat the clock,"], ["🗣️", "one sentence for each prompt."]], sample: "My best friend is funny."},
      {type: "thisorthat", stage: "Get to Know You", heading: "Why English?", pairs: [["To make friends", "For school"], ["To travel", "For my future job"]], why: "Tell me more! Use because.", instruction: [["⚖️", "Pick one,"], ["🗣️", "then explain your choice."]]},
      {type: "practice", stage: "Get to Know You", heading: "My English Goal", line: "I want to learn English because ___. One day I want to ___ in English.", instruction: [["🌟", "Finish the sentences,"], ["🗣️", "then tell me your English goal."]]},
      {type: "message", stage: "Dream Room", heading: "There Is, There Are", lines: ["*There is* a big bed. · *There are* two lamps.", "The lamp is *next to* the bed. The shoes are *under* the bed.", "I *want* a desk because I like to draw."], instruction: [["👀", "Read the sentences,"], ["🗣️", "then describe a room."]]},
      {type: "vocab", stage: "Dream Room", heading: "Room Things", items: [{label: "bed", pic: "/curriculum/u10-rooms/bed.jpg"}, {label: "lamp", pic: "/curriculum/u2-l1/lamp.avif"}, {label: "desk", pic: "/curriculum/u7-objects/desk.png"}], instruction: [["👀", "Look at the pictures,"], ["🗣️", "and say each one aloud."]]},
      {type: "vocab", stage: "Dream Room", heading: "Rooms", items: [{label: "bedroom", pic: "/curriculum/u10-rooms/bedroom.jpg"}, {label: "kitchen", pic: "/curriculum/u10-rooms/kitchen.jpg"}, {label: "living room", pic: "/curriculum/u10-rooms/living-room.jpg"}], instruction: [["👀", "Look at the pictures,"], ["🗣️", "and say each one aloud."]]},
      {type: "spotlight", stage: "Dream Room", heading: "What Is in the Room?", pic: "/curriculum/u10-scenes/dream-room.jpg", label: "dream room", question: "What do you see in the room?", answer: "There is a bed and a lamp.", instruction: [["👂", "Listen,"], ["🗣️", "then say the answer."]]},
      {type: "picmatch", stage: "Find It", heading: "Find It", pool: [{label: "bed", pic: "/curriculum/u10-rooms/bed.jpg"}, {label: "lamp", pic: "/curriculum/u2-l1/lamp.avif"}, {label: "desk", pic: "/curriculum/u7-objects/desk.png"}, {label: "chair", pic: "/curriculum/u7-objects/chair.png"}, {label: "bedroom", pic: "/curriculum/u10-rooms/bedroom.jpg"}, {label: "kitchen", pic: "/curriculum/u10-rooms/kitchen.jpg"}], rounds: [{word: "desk", answer: "desk", choices: ["desk", "chair", "lamp"]}, {word: "lamp", answer: "lamp", choices: ["lamp", "bed", "desk"]}, {word: "kitchen", answer: "kitchen", choices: ["kitchen", "bedroom", "chair"]}, {word: "bed", answer: "bed", choices: ["bed", "chair", "desk"]}], instruction: [["👀", "Read the word,"], ["👆", "then tap the right picture."]]},
      {type: "quiz", stage: "Dream Room", heading: "Pick the Word", rounds: [{q: "___ is a big bed.", options: ["There", "They", "It"], answer: "There"}, {q: "There ___ two lamps.", options: ["are", "is", "am"], answer: "are"}, {q: "The lamp is ___ the bed.", options: ["next to", "at", "for"], answer: "next to"}, {q: "I ___ a desk in my room.", options: ["want", "wants", "wanting"], answer: "want"}], instruction: [["🤔", "Read the sentence,"], ["👆", "then pick the best answer."]]},
      {type: "build", stage: "Build It", heading: "Build the Sentence", rounds: [{words: ["There", "is", "a", "big", "bed", "in", "my", "room."]}, {words: ["The", "lamp", "is", "next", "to", "the", "desk."]}], instruction: [["🧩", "Tap the words in order,"], ["🗣️", "then say the sentence out loud."]]},
      {type: "dice", stage: "Room Dice", heading: "Room Dice", dice: [{name: "There is", items: ["a big bed", "a soft chair", "a tall lamp", "a small desk", "a red door", "a round rug"]}, {name: "Place", items: ["next to the window", "under the lamp", "in my bedroom", "near the door", "in the corner", "in my dream room"]}], instruction: [["🎲", "Roll the dice,"], ["🗣️", "then make a sentence with all three."]]},
      {type: "roleplay", stage: "Design My Room", heading: "Design My Dream Room", situation: "You tell a friend about your dream room. Your friend asks questions.", roles: [{who: "Designer", goal: "Say what is in your room and why you want it."}, {who: "Friend", goal: "Ask what, where and why."}], phrases: ["There is...", "It's next to...", "I want it because..."], instruction: [["🎭", "Read your role,"], ["🗣️", "then act out the scene with your teacher."]]},
      {type: "landing", stage: "Wrap-Up", heading: "Great Job!", caption: "You can describe your dream room."},
    ],
  },
};

export const SPARK_KIDS_LIST = Object.values(SPARK_KIDS_LESSONS);
