// SPARK Kids 1 — Picture Quest
// 20-minute one-to-one online ESL trial lesson for true beginners who are
// still building their alphabet: letter recognition, letter sounds, and
// matching a letter to a picture, through fast, playful mini-games.

export default {
  id: "spark-1",
  code: "SPARK 1",
  title: "Picture Quest",
  subtitle: "Letters, sounds, and pictures for kids just starting their ABCs",
  length: "20 min",
  coreAim: "Get the child recognizing and naming letters, connecting a letter to its sound and a picture, through spinning, flipping, and finding games.",
  hiddenAssessment: "Letter recognition, sound awareness, listening, confidence, and willingness to point, say, and guess.",
  materials: [
    "1 spin wheel with 6 letters (D, C, B, E, L, F), each tied to a picture",
    "5 flippable number cards revealing a letter + matching picture",
    "5 pictures for the I Like / I Don't Like sort",
    "3 hidden mystery pictures for the guessing round",
    "3 letter prompt cards for Find and Show",
  ],
  pacing: [
    { part: "Cover + hello", time: "3 min" },
    { part: "Game 1: Spin the ABC Wheel", time: "4 min" },
    { part: "Game 2: Flip the Letter Cards", time: "4 min" },
    { part: "Game 3: I Like / I Don't Like", time: "3 min" },
    { part: "Game 4: Mystery Letter Box", time: "3 min" },
    { part: "Game 5: Find the Letter", time: "2 min" },
    { part: "Final challenge + feedback", time: "1 min" },
  ],

  introSlides: [
    {
      kind: "intro",
      title: "Let's Go on an ABC Quest!",
      lead: "Today we are going to spin, flip, and find letters together!",
      steps: [
        "Spin the ABC Wheel",
        "Flip the Letter Cards",
        "Find a hidden letter",
        "Win your trophy!",
      ],
    },
  ],

  slides: [
    {
      kind: "wheel",
      title: "Spin the ABC Wheel!",
      purpose: "Open with a high-energy letter game that needs almost no explanation.",
      timing: "4 min",
      teacherScript: ["Spin it!", "What letter?", "Can you say the letter?", "Now say the word!"],
      supportMoves: ["If the child only says the letter, model the full word.", "Teacher: \"D! It's a dog!\" Student repeats."],
      question: "Spin and find a letter!",
      starter: "It's the letter ___.",
      items: [
        { label: "Dog", wheel: "D", icon: "dog" },
        { label: "Cat", wheel: "C", icon: "cat" },
        { label: "Banana", wheel: "B", icon: "banana" },
        { label: "Elephant", wheel: "E", icon: "elephant" },
        { label: "Lion", wheel: "L", icon: "lion" },
        { label: "Fish", wheel: "F", icon: "fish" },
      ],
    },
    {
      kind: "flipcards",
      title: "Flip the Letter Cards!",
      purpose: "Repeat the letter-to-picture connection with a second fun mechanic.",
      timing: "4 min",
      teacherScript: ["Pick a box!", "Flip it!", "What letter do you see?", "What is it?"],
      supportMoves: ["Point at the first letter of the word as you say it together.", "Student: \"Cat.\" Teacher: \"C! C is for cat.\""],
      cards: [
        { number: 1, label: "dog", icon: "dog", category: "animal" },
        { number: 2, label: "cat", icon: "cat", category: "animal" },
        { number: 3, label: "banana", icon: "banana", category: "food" },
        { number: 4, label: "elephant", icon: "elephant", category: "animal" },
        { number: 5, label: "fish", icon: "fish", category: "animal" },
      ],
      starters: ["I pick number ___.", "It's the letter ___.", "It's a ___."],
    },
    {
      kind: "sort",
      title: "I Like / I Don't Like",
      purpose: "Turn letter-naming into a real opinion sentence.",
      timing: "3 min",
      teacherScript: ["What letter is this?", "What is it?", "Do you like it?", "Put it in I like or I don't like."],
      supportMoves: ["Ask for the starting letter first (It starts with ___), then the word, then the opinion.", "Drag the picture into whichever box the child chooses."],
      items: [
        { label: "dog", icon: "dog" },
        { label: "cat", icon: "cat" },
        { label: "banana", icon: "banana" },
        { label: "lion", icon: "lion" },
        { label: "fish", icon: "fish" },
      ],
      idStarter: "It's a ___.",
      likeStarter: "I like ___.",
      dislikeStarter: "I don't like ___.",
    },
    {
      kind: "mystery",
      title: "Mystery Letter Box 1",
      purpose: "Shift from naming to guessing, with the letter as the clue.",
      timing: "1 min",
      teacherScript: ["It starts with... E!", "What do you think it is?", "Reveal it!", "Were you right?"],
      label: "elephant",
      icon: "elephant",
      starter: "I think it's a ___.",
    },
    {
      kind: "mystery",
      title: "Mystery Letter Box 2",
      purpose: "Repeat the guessing mechanic with a new letter clue.",
      timing: "1 min",
      teacherScript: ["It starts with... L!", "What do you think it is this time?", "Reveal it!", "Were you right?"],
      label: "lion",
      icon: "lion",
      starter: "I think it's a ___.",
    },
    {
      kind: "mystery",
      title: "Mystery Letter Box 3",
      purpose: "One more quick guessing round before moving on.",
      timing: "1 min",
      teacherScript: ["It starts with... F!", "What do you think it is?", "Reveal it!", "Were you right?"],
      label: "fish",
      icon: "fish",
      starter: "I think it's a ___.",
    },
    {
      kind: "findshow",
      title: "Find the Letter!",
      purpose: "Move from screen pictures to the child's real environment, and end on an easy win.",
      timing: "2 min",
      teacherScript: ["Find something!", "Show me something that starts with B! Or P! Or T!", "You found it — great job!"],
      prompts: ["something that starts with B", "something that starts with T", "something that starts with P"],
      starter: "I have a ___.",
    },
    {
      kind: "feedback",
      title: "Great Job Today!",
      purpose: "End on a clean, positive note with a parent-ready summary.",
      timing: "1 min",
      childText: ["Great job!", "You know your letters!"],
      feedback: {
        strength: "Good listening, good participation, recognizes several letters and their sounds, willing to repeat and try.",
        target: "Needs more practice with the full alphabet, needs more confidence connecting a letter to its sound without a picture cue, needs more repetition.",
        recommendedPath: "Fun alphabet and phonics classes with picture games and sound practice, building toward Story Quest.",
      },
    },
  ],
};
